pipeline {
    agent any
    tools {
    
        maven 'MAVEN'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Hello World'
                     checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/copykro/java_project.git']])
                   
                    def pomPath = '/var/jenkins_home/workspace/vaccination/demo/pom.xml'
                    
                    sh "mvn -f \"${pomPath}\" -Dmaven.test.failure.ignore=true clean package"
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                script {
               def warFile = sh(
                        script: 'find . -name "*.jar"',
                        returnStdout: true
                    ).trim()
                        def tomcatServer = 'http://172.16.1.105:8080/'
                      def tomcatUser = 'admin'
                      def remotePath = 'C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps'
                      sh "copy ${jarFile} ${remotePath}"
deploy adapters: [tomcat9(credentialsId: '123', path: '', url: 'tomcatServer')], contextPath: null, war:warFile
                }
            }
        }
    }
    post { 
        always {
            junit(allowEmptyResults: true, testResults: '*/test-reports/*.xml')
        }
    }
}
