pipeline {
    agent any
    tools {
    
        maven 'MAVEN'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Hello World'
                     checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/copykro/java_project.git']])
                      sh  "mvn clean package"
                    def pomPath = '/var/jenkins_home/workspace/vaccination/demo/pom.xml'
                    
                    sh "mvn -f \"${pomPath}\" -Dmaven.test.failure.ignore=true clean package"
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                script {
               def warFile = sh(
                        script: 'find . -name "*.jar"',
                        returnStdout: true
                    ).trim()
deploy adapters: [tomcat9(credentialsId: '123', path: '', url: 'http://localhost:8080/')], contextPath: null, war:warFile
                }
            }
        }
    }
    post { 
        always {
            junit(allowEmptyResults: true, testResults: '*/test-reports/*.xml')
        }
    }
}
